// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ControlQuantityController from "./control_quantity_controller"
application.register("control-quantity", ControlQuantityController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import UpdateJackpotController from "./update_jackpot_controller"
application.register("update-jackpot", UpdateJackpotController)
